sudo: false
language: node_js
node_js:
   - "node"
cache:
  directories:
  - src/bower
notifications:
  slack: sap-tools:wXhP1Sbbb9awgdb2wyYpUl9r
before_script:
- bower install
after_script:
- grunt uglify && grunt mocha_istanbul && grunt coveralls
- npm run snyk-monitor
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'v1.1' ]]; then ./.cf.sh cla-assistant-feature; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then ./.cf.sh cla-assistant-staging; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'release' ]]; then ./.cf.sh cla-assistant; fi
